config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    member do
      get 'like', to: 'posts#like', as: 'like'
      get 'unlike', to: 'posts#unlike', as: 'unlike'
    end
    resources :comments
  end

  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'

  get ':user_id/follow_user', to: 'pages#follow', as: 'follow_user'
  get ':user_id/unfollow_user', to: 'pages#unfollow', as: 'unfollow_user'
  get ':username/followers', to: 'pages#followers', as: 'followers'
  get ':username/followings', to: 'pages#followings', as: 'followings'

  get '/tagged/:tag', to: 'pages#filterByTag', as: 'tagged_with'

  get ':username', to: 'pages#userpage', as: 'userpage'

  root to: 'pages#welcome'
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/follow.rb
class Follow < Socialization::ActiveRecordStores::Follow
end

app/models/like.rb
class Like < Socialization::ActiveRecordStores::Like
end

app/models/mention.rb
class Mention < Socialization::ActiveRecordStores::Mention
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments
  acts_as_likeable

  has_attached_file :image, styles: { medium: "550x550>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :category_id, presence: true
  validates :content, presence: true
  validates :image, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :login
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "40x40#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_many :posts
  has_many :comments

  acts_as_followable
  acts_as_follower
  acts_as_liker


  def self.find_for_database_authentication(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["username = :value OR lower(email) = lower(:value)", { :value => login }]).first
      elsif conditions.has_key?(:username) || conditions.has_key?(:email)
        where(conditions.to_hash).first
      end
  end

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  protect_from_forgery with: :null_session

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :name, :avatar,:bio, :password, :password_confirmation, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.post_id = params[:post_id]
    @comment.save
    respond_to do |format|
      # format.html{ redirect_to :back }
      format.js {}
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html{ redirect_to :back }
      format.js {}
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  before_action :authenticate_user!, only:[:follow,:unfollow,:dashboard]

  def welcome
    if user_signed_in?
      redirect_to dashboard_path
    else
      render :layout => false
    end
  end

  def dashboard
    @posts = Post.order(created_at: :desc)
    @post = Post.new
  end

  def search
  end

  def filterByTag
    @category = Category.find_by(name: params[:tag])
    @posts = @category.posts.order(created_at: :desc)
  end

  def userpage
    @user = User.find_by(username: params[:username])
    @posts = @user.posts.order(created_at: :desc)
  end


  def follow
    @user = User.find(params[:user_id])
    current_user.follow!(@user)
    respond_to do |format|
      format.html{ redirect_to :back}
      format.js{}
    end
  end

  def unfollow
    @user = User.find(params[:user_id])
    current_user.unfollow!(@user)
    respond_to do |format|
      format.html{ redirect_to :back}
      format.js{}
    end
  end

  def followers
    @user = User.find_by(username: params[:username])
    @users = @user.followers(User)
  end

  def followings
    @user = User.find_by(username: params[:username])
    @users = @user.followees(User)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except:[:index,:show]

  def index
    @posts = Post.all.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      respond_to do |format|
        format.html{ redirect_to post_path(@post) }
      end
    else
      render action: 'new' 
    end
  end

  def show
    @post = Post.find(params[:id])
    # @comments = @post.comments.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:post_id])
  end

  def update
    @post = Post.find(params[:post_id])
    @post.update(post_params)
    respond_to do |format|
      format.html{ redirect_to post_path(@post) }
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @post.destroy
    respond_to do |format|
      format.html{ redirect_to posts_path }
    end
  end

  def like
    @post = Post.find(params[:id])
    current_user.like!(@post)
    respond_to do |format|
      format.html{ redirect_to :back}
      format.js{}
    end
  end

  def unlike
    @post = Post.find(params[:id])
    current_user.unlike!(@post)
    respond_to do |format|
      format.html{ redirect_to :back}
      format.js{}
    end
  end


  private
    def post_params
      params.require(:post).permit(:image,:content,:category_id)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="media comment" data-id=<%= comment.id %>>
	<div class="media-left">
		<%= link_to image_tag(comment.user.avatar.url(:thumb), class: 'img-circle') %>
	</div>
	<div class="media-body comment-body">
		<%= link_to comment.user.username, userpage_path(comment.user.username) %>  <%= comment.content %>  <span class="time-ago"><%= time_ago_in_words(comment.created_at) %> ago</span><span class="destroy"><%= link_to fa_icon("times 1x"), 	post_comment_path(post_id: comment.post.id, id: comment.id), method: :delete, remote: true %></span>
	</div>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for(Comment.new, url: post_comments_path(post.id), html:{remote: true,class: 'comment-form', id: post.id}) do |f| %>
  <%= f.input :content,as: :string,label: false, input_html:{placeholder: "Your word"} %>
  <%= f.submit "Comment", class: 'btn btn-primary' %>
<% end %>

app/views/comments/create.js.erb
$('.post-comments-dash').css('display','block');
$('form.comment-form[id=<%= @comment.post.id %>]')[0].reset();
$('.post-comments[data-id=<%= @comment.post.id %>]').append("<%= escape_javascript render(partial: 'comment', locals:{comment: @comment}) %>");

app/views/comments/destroy.js.erb
$('.comment[data-id=<%= @comment.id %>]').fadeOut('slow').remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InnFact</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'http://malsup.github.com/jquery.form.js', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "InnFact", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Home", dashboard_path %></li>
        <li><%= link_to "Compose Post", new_post_path %></li>
        <li><%= link_to current_user.username, userpage_path(current_user.username) %></li>
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>

    </ul>
  </div>
</nav>
<div class="container-fluid">

  <%= yield %>

</div>

</body>
</html>

app/views/pages/_user.html.erb
<div class="col-md-3">
	<div class="usercard">
		<%= image_tag(user.avatar.url(:medium),class: 'img-circle img-responsive') %>
		<h4 class="user-name">
			<% if !user.name.present? %> 
				<%= link_to user.username, userpage_path(user.username) %> 
			<% else %> 
				<%= link_to user.name, userpage_path(user.username) %>
			<% end %>
		</h4>
		<h5 class="username">@<%= link_to user.username, userpage_path(user.username) %></h5>
		<% if user_signed_in? and user.id != current_user.id %>
          <% if user.followed_by?(current_user)%>
            <span><%= link_to "Following",unfollow_user_path(user.id),class: 'btn btn-sm btn-success btn-unfollow' %></span>
          <% else %>
            <span><%= link_to "Follow",follow_user_path(user.id),class: 'btn btn-sm btn-success btn-follow' %></span>
          <% end %>
        <% end %>
	</div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-3">
  		<%= image_tag(current_user.avatar.url(:medium), class: 'img-responsive user-avatar-userpage') %>
		<div class="user-info">
			<h4><%= link_to current_user.name, userpage_path(current_user.username) if current_user.name.present? %></h4>
			<span><%= link_to "@#{current_user.username}", userpage_path(current_user.username) %></span>
		</div>
  	</div>
    <div class="col-md-6">
      <%= render partial: 'posts/post', collection: @posts %>
    </div>
  </div>
</div>

app/views/pages/filterByTag.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h4 class="page-header"><%= "Tagged with: #{@category.name}" %></h4>
      <%= render partial: 'posts/post', collection: @posts %>
    </div>
  </div>
</div>

app/views/pages/followers.html.erb
<div class="container">
	<div class="row">
		<% if @users.present? %>
			<%= render partial: 'user',collection: @users %>
		<% else %>
			<div class="not-found">
				<h4>No User Found</h4>
			</div>
		<% end %>
	</div>
</div>

app/views/pages/followings.html.erb
<div class="container">
	<div class="row">
		<% if @users.present? %>
			<%= render partial: 'user',collection: @users %>
		<% else %>
			<div class="not-found">
				<h4>No User Found</h4>
			</div>
		<% end %>
	</div>
</div>

app/views/pages/userpage.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= image_tag(@user.avatar.url(:medium), class: 'img-responsive user-avatar-userpage') %>
      <div class="user-info">
        <h4><%= link_to @user.name, userpage_path(@user.username) if @user.name.present? %></h4>
        <span><%= link_to "@#{@user.username}", userpage_path(@user.username) %></span>
      </div>
    </div>
    <div class="col-md-6">
      <div class="user-bio">
        <article>
          <% if @user.bio.present? %>
            <h5>INTRODUCTION</h5>
            <p><%= @user.bio %></p>
          <% end %>
          <div class="user-stats">
            <span class="follower-counter"><%= link_to pluralize(@user.followers(User).count,"Follower"), followers_path(@user.username) %></span>
              <% if user_signed_in? and @user.id != current_user.id %>
                <% if @user.followed_by?(current_user)%>
                  <span class="follow-action"><%= link_to "Following",unfollow_user_path(@user.id),class: 'btn btn-success' %></span>
                <% else %>
                  <span class="follow-action"><%= link_to "Follow",follow_user_path(@user.id),class: 'btn btn-success' %></span>
              <% end %>
            <% end %>
            <span class="followee-counter"><%= link_to pluralize(@user.followees(User).count,"Following"), followings_path(@user.username) %></span>
          </div>
        </article>
      </div>
      <%= render partial: 'posts/post', collection: @posts %>
    </div>
  </div>
</div>

app/views/pages/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InnFact</title>
  <%= stylesheet_link_tag    'welcome/welcome', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "InnFact", root_path, class: 'navbar-brand' %>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><%= link_to "Home", dashboard_path %></li>
        <li><%= link_to "Compose Post", new_post_path %></li>
        <li><%= link_to current_user.username, userpage_path(current_user.username) %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>

    </ul>
  </div>
</nav>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="welcome-main">
        <h3>Let The Images Speak Out</h3>
        <div class="actions">
          <div class="join"></div>
          <div class="signin"></div>
        </div>
      </div>
    </div>
  </div>

</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for(@post,html:{multipart: true}) do |f| %>

  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :image, label: false %>
  </div>
  <div class="form-group">
    <%= f.input :content, label: false, input_html:{placeholder: "Caption"} %>
  </div>
  <div class="form-ggroup">
  	<%= f.association :category,as: :select%>
  </div>
  <div class="form-action">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="post" data-id= <%= post.id %>>
  <div class="media">
    <div class="media-left">
      <%= image_tag(post.user.avatar.url(:thumb),class: 'img-user-thumb img-circle')%>
    </div>
    <div class="media-body">
      <label class="post-user-name">
        <% if !post.user.name.present? %> 
          <%= link_to post.user.username, userpage_path(post.user.username) %> 
        <% else %> 
          <%= link_to post.user.name, userpage_path(post.user.username) %>
        <% end %>
      </label>
      <br/>
      <span class="time-ago-post"><%= time_ago_in_words(post.created_at) %></span>
    </div>
  </div>

  <div class="post-body">
    <%= link_to image_tag(post.image.url(:medium),class: 'img-responsive'), post_path(post.id) %>
    <%= link_to "##{post.category.name.upcase}",tagged_with_path(post.category.name), class: 'btn btn-info post-tag-link' %>
    <p class="img-caption">
      <%= post.content %>
    </p>
  </div>

  <div class="media post-footer">
    <div class="media-left">
      <% if user_signed_in? %>
        <% if current_user.likes?(post) %>
          <%= link_to fa_icon("heart lg", text: "Liked"),"#",remote: true,onclick: "unlikePost(#{post.id})",data:{id: post.id},class: 'btn btn-danger btn-sm unlike-btn' %>
        <% else %>
          <%= link_to fa_icon("heart-o lg", text: "Like"),"#",remote: true,onclick: "likePost(#{post.id})",data:{id: post.id},class: 'btn btn-default btn-sm like-btn' %>
        <% end %>
      <% end %>
    </div>
    <div class="media-body">
      <span class="likes-counter"><%= fa_icon("heart-o",text: post.likers(User).count) %></span>
      <span class="comments-counter"><%= fa_icon("comments-o",text: post.comments.count) %></span>
    </div>

    <% if user_signed_in? %>
      <div class="comment-form">
        <%= render partial: 'comments/form', locals:{post: post} %>
      </div>
      <div class="post-comments post-comments-dash" data-id=<%= post.id %>>
        
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>EDIT POST</h3>
      <hr/>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <!-- <%= image_tag(current_user.avatar.url(:medium),class: 'img-responsive img-rounded') %> -->
    </div>
    <div class="col-md-6">
      <div class="posts-feed">
        <%= render partial: 'post', collection: @posts %>
      </div>
    </div>
  </div>
</div>

app/views/posts/like.js.erb
$('a.like-btn[data-id=<%= @post.id %>]').removeClass('btn-default like-btn').addClass('btn-danger unlike-btn').html('<%= fa_icon("heart lg",text: "Liked")%>').attr('onclick','unlikePost(<%= @post.id%>)');

app/views/posts/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <div class="post-form">
      <h3>Compose Post</h3>
      <%= render partial: 'form' %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="post" data-id= <%= @post.id %>>
		  <div class="media">
		    <div class="media-left">
		      <%= image_tag(@post.user.avatar.url(:thumb),class: 'img-user-thumb img-circle')%>
		    </div>
		    <div class="media-body">
		      <label class="post-user-name">
		        <% if !@post.user.name.present? %> 
		          <%= link_to @post.user.username, userpage_path(@post.user.username) %> 
		        <% else %> 
		          <%= link_to @post.user.name, userpage_path(@post.user.username) %>
		        <% end %>
		      </label>
		      <br/>
		      <span class="time-ago-post"><%= time_ago_in_words(@post.created_at) %></span>
		    </div>
		  </div>

		  <div class="post-body">
		    <%= image_tag(@post.image.url(:medium),class: 'img-responsive') %>
		    <%= link_to "##{@post.category.name.upcase}",tagged_with_path(@post.category.name), class: 'btn btn-info post-tag-link' %>
		    <p class="img-caption">
		      <%= @post.content %>
		    </p>
		  </div>

		  <div class="media post-footer">
		    <div class="media-left">
		      <% if user_signed_in? %>
		        <% if current_user.likes?(@post) %>
		          <%= link_to fa_icon("heart lg", text: "Liked"),"#",remote: true,onclick: "unlikePost(#{@post.id})",data:{id: @post.id},class: 'btn btn-danger btn-sm unlike-btn' %>
		        <% else %>
		          <%= link_to fa_icon("heart-o lg", text: "Like"),"#",remote: true,onclick: "likePost(#{@post.id})",data:{id: @post.id},class: 'btn btn-default btn-sm like-btn' %>
		        <% end %>
		      <% end %>
		    </div>
		    <div class="media-body">
		      <span class="likes-counter"><%= fa_icon("heart-o",text: @post.likers(User).count) %></span>
		      <span class="comments-counter"><%= fa_icon("comments-o",text: @post.comments.count) %></span>
		    </div>
		  </div>

		  <% if user_signed_in? %>
		    <div class="comment-form">
		      <%= render partial: 'comments/form', locals:{post: @post} %>
		    </div>
		    <div class="post-comments" data-id=<%= @post.id %>>
		    	<% @comments = @post.comments.order(created_at: :desc) %>
		        <%= render partial: 'comments/comment', collection: @comments %>
		    </div>
		  <% end %>
		</div>
    </div>
  </div>
</div>

app/views/posts/unlike.js.erb
$('a.unlike-btn[data-id=<%= @post.id %>]').removeClass('btn-danger unlike-btn').addClass('btn-default like-btn').html('<%= fa_icon("heart-o lg",text: "Like")%>').attr('onclick','likePost(<%= @post.id%>)');